apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 60Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.100.1.215:3260
     iqn: iqn.2005-10.org.freenas.ctl:k8s-iscsi
     lun: 0
     fsType: 'ext4'
     readOnly: false
