apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.11.1
  image: fatwookie/enterprise-es:7.11.1
  nodeSets:
  - name: default
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
      xpack.security.authc.realms:
        native:
          native1: 
            order: 1
            enabled: true
        active_directory:
          active_dir1:
            order: 2
            enabled: true
            domain_name: ad.bodenstab.loc
            url: ldaps://adc1.ad.bodenstab.loc:3269
            ssl:
              verification_mode: none
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            requests:
              memory: 4Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 1
    # request 10Gi of persistent data storage for pods in this topology element
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: espv-local
        resources:
          requests:
            storage: 20Gi
  http:
    service:
      spec:
        type: LoadBalancer
