[all:vars]
ansible_python_interpreter=/usr/bin/python3

[k8s-master]
k8s-master1.bodenstab.loc
k8s-master2.bodenstab.loc

[k8s-node]
k8s-node1.bodenstab.loc
k8s-node2.bodenstab.loc

[k8s]
k8s-node
k8s-master